imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @CPTermsBundle/Resources/config/config.yml }

framework:
    csrf_protection:            ~
    default_locale:             "%locale%"
    #esi:             ~
    form:                       ~
    fragments:                  ~
    router:
        resource:               "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    secret:                     %secret%
    session:
        cookie_domain:          .%cookie_domain%
        handler_id:             session.handler.pdo
        name:                   cptermsdemo
    templating:
        engines: [              'twig']
        #assets_version: SomeVersionScheme
    translator:
        enabled:                true
        fallback:               "%locale%"
    trusted_proxies:            ~
    validation:
        enabled:                true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - CPTermsBundle
        - CPTermsDemoBundle
        - FOSUserBundle

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# FOSUser configuration
fos_user:
    db_driver: propel
    firewall_name: main
    user_class: FOS\UserBundle\Propel\User
    resetting:
        email:
            from_email:
                address: webmaster@coopers-peele.com
                sender_name: CPTermsDemo
            template: 'FOSUserBundle:Resetting:email.html.twig'
        token_ttl: 900
    registration:
        form:
            type:
                admin_user_registration
            validation_groups: ~
    service:
        mailer: fos_user.mailer.twig_swift


propel:
    dbal:
        driver:   "%database_driver%"
        user:     "%database_user%"
        password: "%database_password%"
        dsn:      "%database_driver%:host=%database_host%;dbname=%database_name%;charset=%database_charset%"
        options:  {}
        attributes: {}
    build-properties:
        propel.mysql.tableType: "InnoDB"

#session Configuration
parameters:
    pdo.db_options:
        db_table:        user_session
        db_id_col:       id
        db_data_col:     data
        db_time_col:     time

services:
    pdo:
        class: PDO
        arguments:
            dsn:      "mysql:dbname=%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
    encryption: %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    port:       %mailer_port%

# CPTerms configuration
cp_terms:
    # date_format:    dd MMM yy hh:mm
    entity_finder:
        enabled: true
        #service: cp_terms.entity_finder.fos_user.propel
    # agreement:
    #    show_diff: true
    # markdown:
    #    service: cp_terms.markdown.parser.standard
    diff:
        theme: 'bundles/cptermsdemo/css/diff.css'
