cp_terms_demo:
    resource: "@CPTermsDemoBundle/Controller/"
    type: annotation

cp_terms_bundle:
    resource: "@CPTermsBundle/Resources/config/routing/frontend.yml"

cp_terms_bundle_admin:
    resource: "@CPTermsBundle/Resources/config/routing/admin.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
