security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:             [ROLE_USER, ROLE_CP_TERMS]

    providers:
        fos_userbundle:
            id:                 fos_user.user_provider.username

    firewalls:
        dev:
            pattern:            ^/(_(profiler|wdt)|css|images|js)/
            security:           false

        main:
            pattern:            ^/
            form_login:
                provider:         fos_userbundle
                csrf_provider:    form.csrf_provider
                login_path:       /login
                check_path:       /login_check
            logout: ~
            anonymous: true
            remember_me:
                key:            HfT0W5EigcOsiNQFIqZs
                lifetime:       14400
                path:           /
                domain:         ~

    access_control:
        - { path: ^/login$,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,     roles: ROLE_ADMIN }
        - { path: ^/,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
